name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CSV_URL: "MLproject/cleaned_data/resume_data_cleaned-labeled.csv"
  MLFLOW_TRACKING_URI: file:./mlruns

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up job
        run: echo "Start CI/CD job"

      - name: Run actions/checkout@v3
        uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      - name: Check Env
        run: echo "CSV_URL=$CSV_URL"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r MLproject/requirements.txt

      - name: Set MLflow Tracking URI 
        run: |
          echo "MLFLOW_TRACKING_URI=$MLFLOW_TRACKING_URI" >> $GITHUB_ENV

      - name: Run mlflow project
        run: |
          mlflow run MLproject --env-manager=local 

      - name: Install Python dependencies
        run: |
          pip install mlflow google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

      - name: Upload to Google Drive
        env:
          GDRIVE_CREDENTIALS: ${{ secrets.GDRIVE_CREDENTIALS }}
          GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
        run: |
          python MLproject/upload_to_drive.py